name: 'Generar PDF'

on:
  push:
    branches: [ '*' ]
    paths:
      - 'articulos/**'
      - 'scripts/generar/**'
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: scripts/generar

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: |
        sudo apt update
    - run: |
        sudo apt install make pandoc texlive-latex-base texlive-latex-recommended texlive-pictures texlive-latex-extra
    - run: |
        npm install
    - run: |
        make
    - run: |
        mkdir -p ../../pdf
        cp output/constitucion.pdf ../../pdf
    - uses: EndBug/add-and-commit@v8
      with:
        add: 'pdf'
        author_name: GitHub Actions
        author_email: juancri@juancri.com
        message: 'Actualizando borrador en PDF'
